# Site settings
title: Hank Kim
url: "https://hankyul-kim.github.io"
baseurl: ""
description: >
    Hank Kim blog

# My information
email: hank.kim@outlook.com
author: Hank Kim
profile: Data Analyst
#twitter_username: John_Grib
github_username: hankyul-kim
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: hankkim90
  shortname: Hank
utterances:
  repo: hankyul-kim/hankyul-kim.github.io
  issue-term: pathname
  label: Comment
  branch: master

google_analytics:
  ua: UA-110224147-1

google_adsense:
  client: ca-pub-3675948545737694

blame: "https://github.com/johngrib/johngrib.github.io/blame/master/_wiki"
edit: "https://github.com/johngrib/johngrib.github.io/edit/master/_wiki"
issue: "https://github.com/johngrib/johngrib.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
